<?php
class A{
//    private $name;
//    private static $name;  //ebar baire theke access kora jabena
//    static $name; //Baire theke access kora jasse
    protected static $name;


    static function sayHi(){
//        $this->name = "Hello";  //object die instance hossena tai hobena
        self::$name = "Hello";  //Baire theke access kora jasse
        echo "Hi from A\n";
    }
}

class B extends A{
    static function sayHi()
    {
//        echo parent::sayHi();  //taholeo access korte parbo na
//        parent::sayHi();
        echo "Hi from B\n";
        parent::sayHi(); // TODO: Change the autogenerated stub
    }
}

B::sayHi();
//echo B::$name; //Baire theke access kora jasse